- hosts: localhost
  collections:
    - awx.awx
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Add tower machine credential
      tower_credential:
        name: azure
        description: Team Description
        organization: Default
        credential_type: "Microsoft Azure Resource Manager"
        inputs:
          client: "{{hostvars['localhost']['credentials'][0]['user']}}"
          secret: "{{hostvars['localhost']['credentials'][0]['token']}}"
          tenant: "{{hostvars['localhost']['credentials'][0]['extra_properties']['tenant']}}"
          subscription: "{{hostvars['localhost']['credentials'][0]['extra_properties']['subscription_id']}}"
        state: present
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        tower_host: "{{ awx_base_url }}"
      register: credential_resp