- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - file:
        path: /var/lib/awx/.azure/
        state: directory

    - ini_file:
        path: /var/lib/awx/.azure/credentials
        section: default
        option: "{{item.option}}"
        value: "{{item.value}}"
      with_items:
        - { option: client_id, value: "{{ hostvars['localhost']['user'] }}" }
        - { option: tenant_id, value: "{{ hostvars['localhost']['extra_properties']['tenant'] }}" }
        - { option: subscription_id, value: "{{ hostvars['localhost']['extra_properties']['subscription_id'] }}" }
        - { option: secret, value: "{{ hostvars['localhost']['token'] }}" }

    - name: get_credential_type
      uri:
        method: GET
        validate_certs: no
        follow_redirects: all
        user: "{{ hostvars['localhost']['awx_username'] }}"
        password: "{{ hostvars['localhost']['awx_password'] }}"
        url: "{{ hostvars['localhost']['awx_base_url'] }}/credential_types/"
        return_content: yes
      register: credential_type_resp


    - debug:
        var: credential_type_resp