- hosts: localhost
  collections:
    - awx.awx
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

#
#    - ini_file:
#        path: /var/lib/awx/.azure/credentials
#        section: default
#        option: "{{item.option}}"
#        value: "{{item.value}}"
#      with_items:
#        - { option: client_id, value: "{{ hostvars['localhost']['user'] }}" }
#        - { option: tenant_id, value: "{{ hostvars['localhost']['extra_properties']['tenant'] }}" }
#        - { option: subscription_id, value: "{{ hostvars['localhost']['extra_properties']['subscription_id'] }}" }
#        - { option: secret, value: "{{ hostvars['localhost']['token'] }}" }

#    - file:
#        path: /var/lib/awx/tower_cli.cfg
#        state: touch
#
#    - name: tower conf
#      lineinfile:
#        dest: /var/lib/awx/tower_cli.cfg
#        line: "{{ item }}"
#      with_items:
#        - "host: {{ awx_base_url }}"
#        - "verify_ssl: False"
#        - "tower_username: {{ awx_username }}"
#        - "tower_password: {{ awx_password }}"


    - name: Add tower machine credential
      tower_credential:
        name: azure
        description: Team Description
        organization: Default
        credential_type: azure_rm
        inputs:
          client: "{{hostvars['localhost']['credentials'][0]['user']}}"
          secret: "{{hostvars['localhost']['credentials'][0]['token']}}"
          tenant: "{{hostvars['localhost']['credentials'][0]['extra_properties']['tenant']}}"
          subscription: "{{hostvars['localhost']['credentials'][0]['extra_properties']['subscription_id']}}"
        state: present
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        tower_host: "{{ awx_base_url }}"

#        tower_config_file: /var/lib/awx/tower_cli.cfg




#    - name: get_credential_type
#      uri:
#        method: GET
#        validate_certs: no
#        follow_redirects: all
#        user: "{{ hostvars['localhost']['awx_username'] }}"
#        password: "{{ hostvars['localhost']['awx_password'] }}"
#        url: "{{ hostvars['localhost']['awx_base_url'] }}/credential_types/"
#        return_content: yes
#      register: credential_type_resp
#
#
#    - debug:
#        var: credential_type_resp
