- hosts: localhost
  collections:
    - awx.awx
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
#    - file:
#        path: /var/lib/awx/.azure/
#        state: directory
#
#    - ini_file:
#        path: /var/lib/awx/.azure/credentials
#        section: default
#        option: "{{item.option}}"
#        value: "{{item.value}}"
#      with_items:
#        - { option: client_id, value: "{{ hostvars['localhost']['user'] }}" }
#        - { option: tenant_id, value: "{{ hostvars['localhost']['extra_properties']['tenant'] }}" }
#        - { option: subscription_id, value: "{{ hostvars['localhost']['extra_properties']['subscription_id'] }}" }
#        - { option: secret, value: "{{ hostvars['localhost']['token'] }}" }

    - copy:
        content: "{{ item }}"
        dest: /var/lib/awx/config_file
      with_items:
        - "host: {{awx_base_url}}"
        - "verify_ssl: False"
        - "tower_username: {{ awx_username }}"
        - "tower_password: {{ awx_password }}"

    - name: Add tower machine credential
      tower_credential:
        name: azure
        description: Team Description
        organization: Default
        kind: azure_rm
        tenant: "{{hostvars['localhost']['credentials'][0]['extra_properties']['tenant']}}"
#        inputs:
#          client: "{{hostvars['localhost']['credentials'][0]['user']}}"
#          secret: "{{hostvars['localhost']['credentials'][0]['token']}}"
#          tenant": "{{hostvars['localhost']['credentials'][0]['extra_properties']['tenant']}}"
#          subscription: "{{hostvars['localhost']['credentials'][0]['extra_properties']['subscription_id']}}"
        state: present
        tower_config_file: /var/lib/awx/config_file




#    - name: get_credential_type
#      uri:
#        method: GET
#        validate_certs: no
#        follow_redirects: all
#        user: "{{ hostvars['localhost']['awx_username'] }}"
#        password: "{{ hostvars['localhost']['awx_password'] }}"
#        url: "{{ hostvars['localhost']['awx_base_url'] }}/credential_types/"
#        return_content: yes
#      register: credential_type_resp
#
#
#    - debug:
#        var: credential_type_resp
me_password, become_username, client, description, domain, host, kind, name, organization, password, project, secret, security_token, ssh_key_data, ssh_key_unlock, state, subscription, team, tenant, tower_config_file, tower_host, tower_password, tower_username, user, username, validate_certs, vault_id, vault_password"}
