- hosts: localhost
  vars:
  tasks:
    - set_fact:
        random_resourcegrou_name: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - azure_rm_resourcegroup:
        name: "sdia_{{ random_resourcegrou_name }}"
        location: "{{hostvars['localhost']['domain']}}"
        tags:
          creator: sdia
      register: resourcegroup_output


    - debug:
        var: resourcegroup_output

