- hosts: all
  become: yes
  tasks:
  
    - name: Wait for automatic system updates
      shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 3; done;
      with_items:
        - lock
        - lock-frontend
          
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python    
      
    - name: Install Python
      raw: apt -y update && apt install -y python-minimal
      when: check_python.rc != 0    
      
#     - name: autoremove and autoclean
#       apt: 
#         autoclean: yes
#         autoremove: yes          
      
#     - name: Update and upgrade apt packages
#       apt:
#         upgrade: yes
#         update_cache: yes 
        
#     - name: Install aptitude using apt
#       apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
      
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - ca-certificates
        - apt-transport-https
        - curl
        - gnupg2
        - software-properties-common        
        - python3-pip
        - python-pip      
        - virtualenv
        - firewalld
