- hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: purge kube*
      shell: apt purge kube* -y

    - name: Clean files
      file:
        state: absent
        path: "{{item}}"
      with_items:
        - /etc/cni/
        - /opt/cni/
        - /etc/apt/sources.list.d/apt_kubernetes_io.list
        - /etc/apt/sources.list.d/apt_kubernetes_io.list.save
